# -*- coding: utf-8 -*-
"""Code_challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18vrwUvDJ4pBCOo23Jm8JfJdlrVp-tPpq

Utilizar Python o Java para escribir un script que simule la extracción de datos desde una fuente. Puede ser una API ficticia o un archivo CSV.
"""

import requests
r = requests.get("https://demodata.grapecity.com/northwind/api/v1/Orders")

print(r.json())

"""Limpiar y transformar los datos: eliminar registros duplicados."""

datos= r.json()

def encontrar_duplicados(datos, campo):
  elementos_vistos = set()
  sin_duplicados = []

  for x in datos:
    valor_campo = x.get(campo)

    if valor_campo not in elementos_vistos:
      sin_duplicados.append(x)
      elementos_vistos.add(valor_campo)

  return sin_duplicados

datos_listos = encontrar_duplicados(datos,'orderId')

for x in datos_listos:
  print(x)

"""Completar valores faltantes con pandas:"""

import pandas as pd

datos_listos_df = pd.DataFrame(datos_listos)
print(datos_listos_df)

print(datos_listos_df.fillna("DESCONOCIDO"))

#Con esto tenemos el reemplazo de valores faltantes por la palabra DESCONOCIDO
datos_completos=datos_listos_df.fillna("DESCONOCIDO")
print(datos_completos)